"""
======================================================================
HEC-RAS BINGHAM ENSEMBLE — SENSITIVITY ANALYSIS
by Raka Ghifari (2026)
======================================================================

Perform sensitivity analysis of the primary spatial performance metric.

Primary response variable
-------------------------
    IoU at the configured primary depth threshold.

Methods
-------
    1. Pearson correlation
    2. Spearman rank correlation
    3. Kendall rank correlation
    4. Standardized multiple regression
    5. Partial Rank Correlation Coefficient (PRCC)
    6. Top-25% IoU parameter characterization

The analysis is based on the spatial validation results generated by
05_spatial_validation.py.

The number of ensemble scenarios is determined automatically from
the spatial validation CSV.

Required packages
-----------------
    scipy
    pandas
    numpy

Required configuration
----------------------
    SPATIAL_VALIDATION_CSV
    PRIMARY_DEPTH_THRESHOLD

Optional configuration
----------------------
    ENSEMBLE_DIR
    SENSITIVITY_PARAMETERS

Default sensitivity parameters:

    Cv
    Yield_Stress_Pa
    Viscosity_Pa_s

Output files
------------
    IoU_parameter_correlations.csv
    IoU_standardized_regression.csv
    IoU_PRCC.csv
    IoU_top25_parameter_region.csv
    IoU_top25_runs.csv

Notes
-----
The primary depth threshold is controlled through
PRIMARY_DEPTH_THRESHOLD in config.py.

The top-25% ensemble is defined using the 75th percentile of IoU:

    Top-25% = IoU >= IoU_75th_percentile

The standardized regression coefficients are calculated after
standardizing both predictor variables and the response variable.

PRCC is calculated by residualizing each parameter and the response
against all remaining parameters, followed by Pearson correlation
between the residuals.
======================================================================
"""

from pathlib import Path
import sys

import numpy as np
import pandas as pd
from scipy.stats import (
    pearsonr,
    spearmanr,
    kendalltau,
    t,
)


# ======================================================================
# PROJECT ROOT
# ======================================================================

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))


# ======================================================================
# CONFIGURATION
# ======================================================================

try:
    from config.config import (
        SPATIAL_VALIDATION_CSV,
        PRIMARY_DEPTH_THRESHOLD,
    )
except ImportError as exc:
    raise SystemExit(
        "\nConfiguration file not found.\n\n"
        "Please create:\n"
        "    config/config.py\n\n"
        "from:\n"
        "    config/config_template.py\n"
    ) from exc


# ======================================================================
# OPTIONAL CONFIGURATION
# ======================================================================

try:
    from config.config import ENSEMBLE_DIR
except ImportError:
    ENSEMBLE_DIR = ROOT / "results"


try:
    from config.config import SENSITIVITY_PARAMETERS
except ImportError:
    SENSITIVITY_PARAMETERS = [
        "Cv",
        "Yield_Stress_Pa",
        "Viscosity_Pa_s",
    ]


# ======================================================================
# REQUIRED COLUMNS
# ======================================================================

REQUIRED_COLUMNS = [
    "Run",
    "Threshold_m",
    "IoU",
    *SENSITIVITY_PARAMETERS,
]


# ======================================================================
# LOAD SPATIAL VALIDATION RESULTS
# ======================================================================

def load_validation_data(
    validation_csv: Path,
) -> pd.DataFrame:
    """
    Load and validate the spatial validation results.

    Only rows corresponding to the configured primary depth threshold
    are retained.
    """

    if not validation_csv.exists():
        raise FileNotFoundError(
            f"Spatial validation CSV not found:\n"
            f"{validation_csv}"
        )

    df = pd.read_csv(
        validation_csv
    )

    # ------------------------------------------------------------------
    # Validate required columns
    # ------------------------------------------------------------------

    missing = [
        column
        for column in REQUIRED_COLUMNS
        if column not in df.columns
    ]

    if missing:
        raise ValueError(
            "Missing required columns in spatial validation CSV:\n"
            f"{missing}"
        )

    # ------------------------------------------------------------------
    # Select the primary threshold
    # ------------------------------------------------------------------

    df = df[
        np.isclose(
            df["Threshold_m"],
            PRIMARY_DEPTH_THRESHOLD,
        )
    ].copy()

    if df.empty:
        raise ValueError(
            "No spatial validation records were found for "
            f"the primary depth threshold "
            f"{PRIMARY_DEPTH_THRESHOLD} m."
        )

    # ------------------------------------------------------------------
    # Sort by Run
    # ------------------------------------------------------------------

    df["Run"] = (
        df["Run"]
        .astype(int)
    )

    df = (
        df
        .sort_values("Run")
        .reset_index(drop=True)
    )

    # ------------------------------------------------------------------
    # Validate duplicate Run IDs
    # ------------------------------------------------------------------

    if df["Run"].duplicated().any():

        duplicated = (
            df.loc[
                df["Run"].duplicated(),
                "Run",
            ]
            .tolist()
        )

        raise ValueError(
            "Duplicate Run IDs found in the primary-threshold "
            "spatial validation data:\n"
            f"{duplicated}"
        )

    # ------------------------------------------------------------------
    # Validate numerical data
    # ------------------------------------------------------------------

    numeric_columns = [
        "IoU",
        *SENSITIVITY_PARAMETERS,
    ]

    for column in numeric_columns:

        df[column] = pd.to_numeric(
            df[column],
            errors="coerce",
        )

    if df[numeric_columns].isna().any().any():

        invalid_counts = (
            df[numeric_columns]
            .isna()
            .sum()
        )

        invalid_counts = (
            invalid_counts[
                invalid_counts > 0
            ]
        )

        raise ValueError(
            "Missing or non-numeric values were found in "
            "the primary-threshold data:\n"
            f"{invalid_counts.to_dict()}"
        )

    # ------------------------------------------------------------------
    # Validate finite values
    # ------------------------------------------------------------------

    values = df[
        numeric_columns
    ].to_numpy(
        dtype=float
    )

    if not np.isfinite(values).all():

        raise ValueError(
            "Non-finite values were found in the "
            "sensitivity-analysis data."
        )

    return df


# ======================================================================
# RESIDUALIZE
# ======================================================================

def residualize(
    y: np.ndarray,
    controls: np.ndarray,
) -> np.ndarray:
    """
    Remove the linear contribution of control variables from y.

    An intercept is included in the least-squares model.
    """

    controls = np.asarray(
        controls,
        dtype=float,
    )

    y = np.asarray(
        y,
        dtype=float,
    )

    if controls.ndim == 1:
        controls = controls.reshape(
            -1,
            1,
        )

    A = np.column_stack(
        [
            np.ones(
                len(controls)
            ),
            controls,
        ]
    )

    beta = np.linalg.lstsq(
        A,
        y,
        rcond=None,
    )[0]

    return (
        y
        - A @ beta
    )


# ======================================================================
# CALCULATE CORRELATIONS
# ======================================================================

def calculate_correlations(
    X: np.ndarray,
    y: np.ndarray,
    parameters: list[str],
) -> pd.DataFrame:
    """
    Calculate Pearson, Spearman, and Kendall correlations.
    """

    rows = []

    for i, parameter in enumerate(
        parameters
    ):

        x = X[:, i]

        pearson = pearsonr(
            x,
            y,
        )

        spearman = spearmanr(
            x,
            y,
        )

        kendall = kendalltau(
            x,
            y,
        )

        rows.append(
            {
                "Parameter": parameter,
                "Pearson_r": pearson.statistic,
                "Pearson_p": pearson.pvalue,
                "Spearman_rho": spearman.statistic,
                "Spearman_p": spearman.pvalue,
                "Kendall_tau": kendall.statistic,
                "Kendall_p": kendall.pvalue,
            }
        )

    return pd.DataFrame(
        rows
    )


# ======================================================================
# STANDARDIZED MULTIPLE REGRESSION
# ======================================================================

def calculate_standardized_regression(
    X: np.ndarray,
    y: np.ndarray,
    parameters: list[str],
) -> tuple[pd.DataFrame, float, float]:
    """
    Perform standardized multiple linear regression.

    Both predictors and response are standardized using sample
    standard deviation (ddof=1).

    Returns
    -------
    regression:
        Standardized coefficients, standard errors, t statistics,
        and p-values.

    r2:
        Coefficient of determination.

    adjusted_r2:
        Adjusted coefficient of determination.
    """

    n = len(y)
    k = X.shape[1]

    if n <= k + 1:
        raise ValueError(
            "Not enough observations for multiple regression.\n"
            f"Observations: {n}\n"
            f"Parameters: {k}\n"
            f"Required observations: > {k + 1}"
        )

    # ------------------------------------------------------------------
    # Standardize predictors and response
    # ------------------------------------------------------------------

    X_std = (
        X
        - X.mean(axis=0)
    ) / X.std(
        axis=0,
        ddof=1,
    )

    y_std = (
        y
        - y.mean()
    ) / y.std(
        ddof=1
    )

    # ------------------------------------------------------------------
    # Add intercept
    # ------------------------------------------------------------------

    A = np.column_stack(
        [
            np.ones(n),
            X_std,
        ]
    )

    # ------------------------------------------------------------------
    # Least-squares regression
    # ------------------------------------------------------------------

    beta = np.linalg.lstsq(
        A,
        y_std,
        rcond=None,
    )[0]

    # ------------------------------------------------------------------
    # Predictions and residuals
    # ------------------------------------------------------------------

    predicted = (
        A @ beta
    )

    residual = (
        y_std
        - predicted
    )

    # ------------------------------------------------------------------
    # R-squared
    # ------------------------------------------------------------------

    sse = np.sum(
        residual ** 2
    )

    sst = np.sum(
        (
            y_std
            - y_std.mean()
        )
        ** 2)